# Generated by Django 4.2.4 on 2023-08-17 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['name']},
        ),
    ]
