# Generated by Django 4.2.4 on 2023-08-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_question_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
