# Generated by Django 4.2.4 on 2023-10-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_alter_question_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='exam',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(max_length=50),
        ),
    ]
